language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

script:
  - cd emumisc
  - cargo test --verbose
  - cd ../mos6502
  - cargo test --verbose
  - cd ../nes
  - cargo test --verbose
  - cd ../pinky-libretro
  - cargo build --verbose
